---
title: "MLWork"
author: "Hannah Snell"
date: "2/6/2020"
output: html_document
---


LOAD FOLLOWING CODE CHUNKS EACH TIME:
----------------------------------------

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(tidyverse)
```

# Data Preparation 

## Resistance Data 

```{r, include = FALSE}
resistance_state <- read.csv("Resist_States.csv")
resistance_region <- read.csv("Resist_Regional.csv")
resistance_national <- read.csv("Resist_National.csv")
IsolateData_2 <- read.csv("IsolateData-2.csv")
```

## Outpatient Antibiotic Use Data 

```{r, include = FALSE} 
antibiotic_use <- read.csv("Outpatient_Antibiotic_Use.csv") 
antibiotic_use <- antibiotic_use %>% 
  mutate(State = recode(Location, 
                           "Alabama" = "AL",
                           "Alaska" = "AK",
                           "Arizona" = "AZ",
                           "Arkansas" = "AR",
                           "California" = "CA",
                           "Colorado" = "CO",
                           "Connecticut" = "CT",
                           "Delaware" = "DE",
                           "District Of Columbia" = "DC",
                           "Florida" = "FL",
                           "Georgia" = "GA",
                           "Hawaii" = "HI",
                           "Idaho" = "ID",
                           "Illinois" = "IL",
                           "Indiana" = "IN", 
                           "Iowa" = "IA",
                           "Kansas" = "KS",
                           "Kentucky" = "KY",
                           "Louisiana" = "LA", 
                           "Maine" = "ME",
                           "Maryland" = "MD",
                           "Massachusetts" = "MA",
                           "Michigan" = "MI",
                           "Minnesota" = "MN",
                           "Mississippi" = "MS",
                           "Missouri" = "MO",
                           "Montana" = "MT",
                           "Nebraska" = "NE",
                           "Nevada" = "NV",
                           "New Hampshire" = "NH",
                           "New Jersey" = "NJ",
                           "New Mexico" = "NM",
                           "New York" = "NY",
                           "North Carolina" = "NC",
                           "North Dakota" = "ND",
                           "Ohio" = "OH",
                           "Oklahoma" = "OK",
                           "Oregon" = "OR",
                           "Pennsylvania" = "PA",
                           "Rhode Island" = "RI",
                           "South Carolina" = "SC",
                           "South Dakota" = "SD",
                           "Tennessee" = "TN",
                           "Texas" = "TX",
                           "Utah" = "UT",
                           "Vermont" = "VT",
                           "Virginia" = "VA",
                           "Washington" = "WA",
                           "West Virginia" = "WV",
                           "Wisconsin" = "WI",
                           "Wyoming" = "WY"))

```

----------------------------------------

### 20200228

```{r}
isolatedata <- IsolateData_2 %>% 
  select(Genus, Species, Data.Year, Resistance.Pattern)

outpatientdata <- Outpatient_Antibiotic_Use %>% 
  select(Antibiotic_Class, Year, Rate, Location) %>% 
  mutate(Rate = as.numeric(Rate)) %>% 
  filter(Location != "National") %>% 
  mutate(Location = recode(Location, 
                           "Alabama" = "AL",
                           "Alaska" = "AK",
                           "Arizona" = "AZ",
                           "Arkansas" = "AR",
                           "California" = "CA",
                           "Colorado" = "CO",
                           "Connecticut" = "CT",
                           "Delaware" = "DE",
                           "District Of Columbia" = "DC",
                           "Florida" = "FL",
                           "Georgia" = "GA",
                           "Hawaii" = "HI",
                           "Idaho" = "ID",
                           "Illinois" = "IL",
                           "Indiana" = "IN", 
                           "Iowa" = "IA",
                           "Kansas" = "KS",
                           "Kentucky" = "KY",
                           "Louisiana" = "LA", 
                           "Maine" = "ME",
                           "Maryland" = "MD",
                           "Massachusetts" = "MA",
                           "Michigan" = "MI",
                           "Minnesota" = "MN",
                           "Mississippi" = "MS",
                           "Missouri" = "MO",
                           "Montana" = "MT",
                           "Nebraska" = "NE",
                           "Nevada" = "NV",
                           "New Hampshire" = "NH",
                           "New Jersey" = "NJ",
                           "New Mexico" = "NM",
                           "New York" = "NY",
                           "North Carolina" = "NC",
                           "North Dakota" = "ND",
                           "Ohio" = "OH",
                           "Oklahoma" = "OK",
                           "Oregon" = "OR",
                           "Pennsylvania" = "PA",
                           "Rhode Island" = "RI",
                           "South Carolina" = "SC",
                           "South Dakota" = "SD",
                           "Tennessee" = "TN",
                           "Texas" = "TX",
                           "Utah" = "UT",
                           "Vermont" = "VT",
                           "Virginia" = "VA",
                           "Washington" = "WA",
                           "West Virginia" = "WV",
                           "Wisconsin" = "WI",
                           "Wyoming" = "WY")) 

  
  

censusdata <- Census_10_19 %>% 
  select(-`Census`, -`Estimation Base`) %>% 
  pivot_longer(names_to = "Year", 
               values_to = "Population Count", 
               cols = -`Geographic Area`) %>% 
  mutate(Year = as.numeric(Year)) %>% 
  mutate(Location = recode(`Geographic Area`, 
                           ".Alabama" = "AL",
                           ".Alaska" = "AK",
                           ".Arizona" = "AZ",
                           ".Arkansas" = "AR",
                           ".California" = "CA",
                           ".Colorado" = "CO",
                           ".Connecticut" = "CT",
                           ".Delaware" = "DE",
                           ".District Of Columbia" = "DC",
                           ".Florida" = "FL",
                           ".Georgia" = "GA",
                           ".Hawaii" = "HI",
                           ".Idaho" = "ID",
                           ".Illinois" = "IL",
                           ".Indiana" = "IN", 
                           ".Iowa" = "IA",
                           ".Kansas" = "KS",
                           ".Kentucky" = "KY",
                           ".Louisiana" = "LA", 
                           ".Maine" = "ME",
                           ".Maryland" = "MD",
                           ".Massachusetts" = "MA",
                           ".Michigan" = "MI",
                           ".Minnesota" = "MN",
                           ".Mississippi" = "MS",
                           ".Missouri" = "MO",
                           ".Montana" = "MT",
                           ".Nebraska" = "NE",
                           ".Nevada" = "NV",
                           ".New Hampshire" = "NH",
                           ".New Jersey" = "NJ",
                           ".New Mexico" = "NM",
                           ".New York" = "NY",
                           ".North Carolina" = "NC",
                           ".North Dakota" = "ND",
                           ".Ohio" = "OH",
                           ".Oklahoma" = "OK",
                           ".Oregon" = "OR",
                           ".Pennsylvania" = "PA",
                           ".Rhode Island" = "RI",
                           ".South Carolina" = "SC",
                           ".South Dakota" = "SD",
                           ".Tennessee" = "TN",
                           ".Texas" = "TX",
                           ".Utah" = "UT",
                           ".Vermont" = "VT",
                           ".Virginia" = "VA",
                           ".Washington" = "WA",
                           ".West Virginia" = "WV",
                           ".Wisconsin" = "WI",
                           ".Wyoming" = "WY")) %>% 
  select(-`Geographic Area`)



```


#### Calculating for GDP per Cap (aka normalizing per number of prescriptions based on population of people in US)

```{r}
census2011<- censusdata %>% 
  filter(Year == 2011, 
         Location != "United States", 
         Location != "Northeast", 
         Location != "Midwest", 
         Location != "South", 
         Location != "West", 
         Location != "Puerto Rico") 

outpatient2011 <- outpatientdata %>% 
  filter(Year == 2011)

# Merge census2011 and outpatient2011 

gdp2011 <- outpatient2011 %>% 
  left_join(census2011, by = "Location") %>% 
  select(-"Year.y") %>% 
  rename("Year" = Year.x) 

# GDP per Cap Calculation 

gdp2011 <- gdp2011 %>% 
  mutate(GDPperCap = (`Rate`/`Population Count`))
```


_____________________________________________________________________

(Previous Work) 
## IsolateData-2 Set 

```{r}
IsolateData_2 %>% distinct(Species)


# So there are 11 unique species --> This will be easy to work with and make some EDA viz
```

## EDA 

### Enterica
```{r}
isolate_enterica <- IsolateData_2 %>% 
  filter(Species == "enterica") %>% 
  group_by(`Resistance.Pattern`) %>% 
  mutate(ResistCount = n()) %>% 
  filter(ResistCount >= 100) %>% 
  mutate(logResist = log10(ResistCount))

  
testviz1 <- ggplot(data = isolate_enterica, aes(x = `Resistance.Pattern`, y = logResist)) + geom_col() + theme(axis.text.x = element_text(angle = 90)) + ggtitle("Enterica")
testviz1
  

```


### Jejuni

```{r}
isolate_jejuni <- IsolateData_2 %>% 
  filter(Species == "jejuni") %>% 
  group_by(`Resistance.Pattern`) %>% 
  mutate(ResistCount = n()) %>% 
  filter(ResistCount >= 100) %>% 
  mutate(logResist = log10(ResistCount))

  
testviz2 <- ggplot(data = isolate_jejuni, aes(x = `Resistance.Pattern`, y = logResist)) + geom_col() + theme(axis.text.x = element_text(angle = 90))+ ggtitle("Jejuni")
testviz2
```

### Flexneri 

```{r}
isolate_flexneri <- IsolateData_2 %>% 
  filter(Species == "flexneri") %>% 
  group_by(`Resistance.Pattern`) %>% 
  mutate(ResistCount = n()) %>% 
  filter(ResistCount >= 100) %>% 
  mutate(logResist = log10(ResistCount))

  
testviz3 <- ggplot(data = isolate_flexneri, aes(x = `Resistance.Pattern`, y = logResist)) + geom_col() + theme(axis.text.x = element_text(angle = 90)) + ggtitle("Flexneri")
testviz3
```

### Sonnei 

```{r}
isolate_sonnei <- IsolateData_2 %>% 
  filter(Species == "sonnei") %>% 
  group_by(`Resistance.Pattern`) %>% 
  mutate(ResistCount = n()) %>% 
  filter(ResistCount >= 100) %>% 
  mutate(logResist = log10(ResistCount))

  
testviz4 <- ggplot(data = isolate_sonnei, aes(x = `Resistance.Pattern`, y = logResist)) + geom_col() + theme(axis.text.x = element_text(angle = 90)) + ggtitle("Sonnei")
testviz4
```


### Coli 

```{r}
isolate_coli <- IsolateData_2 %>% 
  filter(Species == "coli") %>% 
  group_by(`Resistance.Pattern`) %>% 
  mutate(ResistCount = n()) %>% 
  filter(ResistCount >= 100) %>% 
  mutate(logResist = log10(ResistCount))

  
testviz5 <- ggplot(data = isolate_coli, aes(x = `Resistance.Pattern`, y = logResist)) + geom_col() + theme(axis.text.x = element_text(angle = 90)) + ggtitle("Coli")
testviz5
```

### Boydii 

```{r}
isolate_boydii <- IsolateData_2 %>% 
  filter(Species == "boydii") %>% 
  group_by(`Resistance.Pattern`) %>% 
  mutate(ResistCount = n()) %>% 
  #filter(ResistCount >= 100) %>% 
  mutate(logResist = log10(ResistCount))

  
testviz6 <- ggplot(data = isolate_boydii, aes(x = `Resistance.Pattern`, y = logResist)) + geom_col() + theme(axis.text.x = element_text(angle = 90)) + ggtitle("Boydii")
testviz6

# NOTE: Did not filter for 100+ occurrences! 
```

### Unknown

```{r}
isolate_unknown <- IsolateData_2 %>% 
  filter(Species == "unknown") %>% 
  group_by(`Resistance.Pattern`) %>% 
  mutate(ResistCount = n()) %>% 
  #filter(ResistCount >= 100) %>% 
  mutate(logResist = log10(ResistCount))

  
testviz7 <- ggplot(data = isolate_unknown, aes(x = `Resistance.Pattern`, y = logResist)) + geom_col() + theme(axis.text.x = element_text(angle = 90)) + ggtitle("Unknown")
testviz7

# NOTE: Did not filter for 100+ occurrences! 
```

### Dysenteriae

```{r}
isolate_dysenteriae <- IsolateData_2 %>% 
  filter(Species == "dysenteriae") %>% 
  group_by(`Resistance.Pattern`) %>% 
  mutate(ResistCount = n()) %>% 
  #filter(ResistCount >= 100) %>% 
  mutate(logResist = log10(ResistCount))

  
testviz8 <- ggplot(data = isolate_dysenteriae, aes(x = `Resistance.Pattern`, y = logResist)) + geom_col() + theme(axis.text.x = element_text(angle = 90)) + ggtitle("Dysenteriae")
testviz8
```

### Provisional

```{r}
isolate_provisional <- IsolateData_2 %>% 
  filter(Species == "provisional") %>% 
  group_by(`Resistance.Pattern`) %>% 
  mutate(ResistCount = n()) 
  #filter(ResistCount >= 100) %>% 
  #mutate(logResist = log10(ResistCount))

  
testviz9 <- ggplot(data = isolate_provisional, aes(x = `Resistance.Pattern`, y = ResistCount)) + geom_col() + theme(axis.text.x = element_text(angle = 90)) + ggtitle("Provisonal")
testviz9
```

### Other

```{r}
isolate_other <- IsolateData_2 %>% 
  filter(Species == "other") %>% 
  group_by(`Resistance.Pattern`) %>% 
  mutate(ResistCount = n()) 
  #filter(ResistCount >= 100) %>% 
  #mutate(logResist = log10(ResistCount))

  
testviz10 <- ggplot(data = isolate_other, aes(x = `Resistance.Pattern`, y = ResistCount)) + geom_col() + theme(axis.text.x = element_text(angle = 90)) + ggtitle("Other")
testviz10
```

### Bongori

```{r}
isolate_bongori <- IsolateData_2 %>% 
  filter(Species == "bongori") %>% 
  group_by(`Resistance.Pattern`) %>% 
  mutate(ResistCount = n()) 
  #filter(ResistCount >= 100) %>% 
  #mutate(logResist = log10(ResistCount))

  
testviz11 <- ggplot(data = isolate_bongori, aes(x = `Resistance.Pattern`, y = ResistCount)) + geom_col() + theme(axis.text.x = element_text(angle = 90)) + ggtitle("Bongori")
testviz11
```

```{r}
### Dataset Building! 

# flexneri2011 dataset
flexneri2011 <- IsolateData_2 %>% 
  select(Species, Region.Name, Data.Year, Resistance.Pattern) %>% 
  filter(Data.Year == 2011) %>% 
  filter(Species == "flexneri") 

flexcount <- flexneri2011 %>% 
  group_by(Resistance.Pattern) %>% 
  mutate(count = n()) %>% 
  distinct(count) 

# distribution of resistance 

ggplot(flexcount, aes(x = Resistance.Pattern, y = count)) + geom_col() + theme(axis.text.x = element_text(angle = 90))
  
# antibiotic use data prep 

antibiotic2011 <- antibiotic_use %>% 
  filter(Year == 2011) 

```



























