---
title: "Pratima EDA Wor"
author: "Pratima Niroula"
date: "4/20/2020"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(stringr)
library(readxl)
```

# Data Preparation 

## Import IqVia Data
```{r, cache = TRUE}
iqvia <- read.delim("~/Downloads/PartD_Prescriber_PUF_NPI_Drug_17.txt")
```

```{r}
PARTD_AntibioticGeneric <- read_excel("Data/PARTD_AntibioticGeneric.xlsx")
```

## Make IqVia Dataframes (parse into 5 dataframes)

```{r}
iqvia1 <- iqvia %>% 
  slice(1:5000000)
iqvia2 <- iqvia %>% 
  slice(5000001:10000000) 
iqvia3 <- iqvia %>% 
  slice(10000001:15000000) 
iqvia4 <- iqvia %>% 
  slice(15000001:20000000)
iqvia5 <- iqvia %>% 
  slice(20000001:25209130)
```

## Filter Out Quinonones Class (EDA)

```{r}
#Unique values from partd_antibioticgeneric:
PARTD_AntibioticGeneric[!duplicated(PARTD_AntibioticGeneric$`Generic Name`), ]

#IMPORT IQVIA DATA:
# iqvia1 <- read.csv("~/Downloads/Iqvia Data/iqvia1data.csv")
# iqvia2 <- read.csv("~/Downloads/Iqvia Data/iqvia2data.csv")
# iqvia3 <- read.csv("~/Downloads/Iqvia Data/iqvia3data.csv")
# iqvia4 <- read.csv("~/Downloads/Iqvia Data/iqvia4data.csv")
# iqvia5 <- read.csv("~/Downloads/Iqvia Data/iqvia5data.csv")

#Filter for antibiotic drugs only:
iqvia1 <- filter(iqvia1, generic_name %in% PARTD_AntibioticGeneric$`Generic Name`)
iqvia2 <- filter(iqvia2, generic_name %in% PARTD_AntibioticGeneric$`Generic Name`)
iqvia3 <- filter(iqvia3, generic_name %in% PARTD_AntibioticGeneric$`Generic Name`)
iqvia4 <- filter(iqvia4, generic_name %in% PARTD_AntibioticGeneric$`Generic Name`)
iqvia5 <- filter(iqvia5, generic_name %in% PARTD_AntibioticGeneric$`Generic Name`)

#combine all sets into one
combinediqvia <- rbind(iqvia1, iqvia2, iqvia3, iqvia4, iqvia5)
```

## Filter Out Unnecessary Columns

```{r}
combinediqvia <- combinediqvia %>% 
  select(-nppes_provider_last_org_name, 
         -nppes_provider_first_name, 
         -total_30_day_fill_count, 
         -total_30_day_fill_count_ge65, 
         -total_day_supply, 
         -bene_count_ge65, 
         -bene_count_ge65_suppress_flag, 
         -total_claim_count_ge65,
         -total_30_day_fill_count_ge65, 
         -description_flag, 
         -ge65_suppress_flag, 
         -total_day_supply_ge65, 
         -total_drug_cost_ge65)
```

## Example Figure 

```{r}
totaliqvia2017 <- combinediqvia %>% 
  group_by(generic_name) %>% 
  summarise(totalprescriptioncount = sum(total_claim_count)) %>% 
  arrange(desc(totalprescriptioncount)) %>% 
  head(25)
totaliqvia2017

ggplot(totaliqvia2017, aes(x = reorder(generic_name, -totalprescriptioncount), y = totalprescriptioncount)) + 
  geom_col() + 
  labs(x = "Generic Antibiotic Name", y = "Total Prescription Claims", title = "Count of Top 25 Highest Prescribed Antibiotics in 2017") + 
  theme(axis.text.x = element_text(angle = 90))

```

## Start your EDA Work Here: 

```{r}

```

