---
title: "SereneMLModeling"
author: "Serene Lee"
output: html_document
---

```{r}
library(dplyr)
#Unique values from partd_antibioticgeneric:
PARTD_AntibioticGeneric[!duplicated(PARTD_AntibioticGeneric$`Generic Name`), ]

#IMPORT IQVIA DATA:
iqvia1 <- read.csv("~/Documents/School/Smith Sem 8 LAST SEM/Special Studies/Iqvia Data/iqvia1data.csv")
iqvia2 <- read.csv("~/Documents/School/Smith Sem 8 LAST SEM/Special Studies/Iqvia Data/iqvia2data.csv")
iqvia3 <- read.csv("~/Documents/School/Smith Sem 8 LAST SEM/Special Studies/Iqvia Data/iqvia3data.csv")
iqvia4 <- read.csv("~/Documents/School/Smith Sem 8 LAST SEM/Special Studies/Iqvia Data/iqvia4data.csv")
iqvia5 <- read.csv("~/Documents/School/Smith Sem 8 LAST SEM/Special Studies/Iqvia Data/iqvia5data.csv")

#Filter for antibiotic drugs only:
iqvia1 <- filter(iqvia1, generic_name %in% PARTD_AntibioticGeneric$`Generic Name`)
iqvia2 <- filter(iqvia2, generic_name %in% PARTD_AntibioticGeneric$`Generic Name`)
iqvia3 <- filter(iqvia3, generic_name %in% PARTD_AntibioticGeneric$`Generic Name`)
iqvia4 <- filter(iqvia4, generic_name %in% PARTD_AntibioticGeneric$`Generic Name`)
iqvia5 <- filter(iqvia5, generic_name %in% PARTD_AntibioticGeneric$`Generic Name`)

```



```{r}
library(tidyverse)
library(dplyr)
library(tidyr)
library(reshape2)
library(ggplot2)

resistance_state <- read.csv("~/Documents/School/Smith Sem 7/Special Studies/PSP_Antibiotic_Resistance_Data/Resist_States.csv")

# 2) 
resistance_region <- read.csv("~/Documents/School/Smith Sem 7/Special Studies/PSP_Antibiotic_Resistance_Data/Resist_Regional.csv")

# 3)
resistance_national <- read.csv("~/Documents/School/Smith Sem 7/Special Studies/PSP_Antibiotic_Resistance_Data/Resist_National.csv")

```


#Medicaid:
##Quinolones/Fluoroquinolones antibiotic drugs:
```{r}
#Generic name of drug (Referenced GoodRx): Ciprofloxacin HCl, Ciprofloxacin, Ciprofloxacin/Hydrocortisone,
#Ciprofloxacin In 5 % Dextrose, Ciprofloxacin HCl/Dexameth, Ciprofloxacin Lactate, Ciprofloxacin/Ciprofloxa HCl, Ciprofloxacin HCl/Fluocinolone, Levofloxacin, Levofloxacin In Dextrose 5 %, Ofloxacin, Moxifloxacin HCl, Moxifloxacin-Sod.Chloride(Iso), Moxifloxacin/Sod.Ace,Sul/Water, Besifloxacin HCl, Delafloxacin Meglumine, Gatifloxacin

# Create a new data set with only drugs under the quinolones antibiotic class:
Medicaid_Quinolone <- Medicaid_SpendingUtilization %>%
  filter(GenericName == "Ciprofloxacin HCl"|
           GenericName == "Ciprofloxacin"|
           GenericName == "Ciprofloxacin/Hydrocortisone"|
           GenericName == "Ciprofloxacin In 5 % Dextrose"|
           GenericName == "Ciprofloxacin HCl/Dexameth"|
           GenericName == "Ciprofloxacin Lactate"|
           GenericName == "Ciprofloxacin/Ciprofloxa HCl"|
           GenericName == "Ciprofloxacin HCl/Fluocinolone"|
           GenericName == "Levofloxacin"|
           GenericName == "Levofloxacin In Dextrose 5 %"|
           GenericName == "Ofloxacin"|
           GenericName == "Moxifloxacin HCl"|
           GenericName == "Moxifloxacin-Sod.Chloride(Iso)"|
           GenericName == "Moxifloxacin/Sod.Ace,Sul/Water"|
           GenericName == "Besifloxacin HCl"|
           GenericName == "Delafloxacin Meglumine"|
           GenericName == "Gatifloxacin")
View(Medicaid_Quinolone)

# EDA to look at trends for spending:
ggplot(data = Medicaid_Quinolone, aes(x = Year, y = TotalSpending)) + geom_point()
ggplot(data = Medicaid_Quinolone, aes(x = Year, y = TotalClaims, col = GenericName)) + geom_jitter()
ggplot(data = Medicaid_Quinolone, aes(x = log10(TotalClaims))) + geom_histogram() + facet_wrap(~Year)
```

#Regional Resistance Data:
```{r}
# Refreshing Regional resistance data
Resist_Regional <- resistance_region %>%
  select(-Lower95CI, -Upper95CI, -PercentResistant)

#Resistance Trends by Region
Resist_Regional <- Resist_Regional %>%
  filter(EventYear != "All Years")

#Change data type
Resist_Regional$NumberTested <- as.numeric(as.character(Resist_Regional$NumberTested))
Resist_Regional$NumberResistant <- as.numeric(as.character(Resist_Regional$NumberResistant))
#Resist_Regional$PercentResistant <- as.numeric(as.character(Resist_Regional$PercentResistant))
Resist_Regional$AgeCategory <- as.character(Resist_Regional$AgeCategory)

# Inserting the average of NumberResistant and NumberTested:
Resist_Regional <- Resist_Regional %>%
  filter(NumberResistant != "Insufficient Data" & NumberResistant != "None Tested" & EventYear != "All Years")

# Plot to see trends in region:
#ggplot(data = Resist_Regional, aes(x = EventYear, y = PercentResistant, col = AgeCategory)) + geom_col()
#ggplot(data = Resist_Regional, aes(x = EventYear, y = PercentResistant)) + geom_col() + facet_wrap(~Region)

```

# Calculate Percent Resistant
```{r}
# Tidy format for Resist_Regional data and take out ALL HAIS and ALL AGES
Resist_Regional <- Resist_Regional %>%
  gather(MetricType, MetricNumber, NumberTested:NumberResistant) %>%
  filter(EventType != "All HAIs", AgeCategory != "All Ages")

# Plot NumberTested and NumberResistant Data
ggplot(data = Resist_Regional, 
       aes(x = EventYear, y = MetricNumber, fill = MetricType)) + 
  geom_col(position = position_dodge(width = 0.5)) + 
  facet_wrap(~Region)

# Regroup data for Calculated PercentResistant Data
Resist_Regional_CalculateResPercent <- Resist_Regional %>%
  group_by(Region, EventYear, MetricType) %>%
  summarize(TotalMetricNumber = sum(MetricNumber))

# Revert Dataset to Wide form
Wide_data_ResistPercent <- spread(Resist_Regional_CalculateResPercent,
                                  MetricType,
                                  TotalMetricNumber)
Wide_data_ResistPercent <- Wide_data_ResistPercent %>%
  mutate(Percent_Resistant = (NumberResistant/NumberTested)*100)

#Wide_data_ResistPercent <- melt(Resist_Regional_CalculateResPercent,
#                                id.vars = c("Region", "EventYear"),
#                                variable.name = "MetricType",
#                                value.name = "TotalMetricNumber")

#Wide_data_ResistPercent <- reshape(Resist_Regional_CalculateResPercent,
#                                   idvar = c("Region", "EventYear"),
#                                   timevar = "MetricType",
#                                   direction = "wide")

# Plot Percent Resistant Data
ggplot(data = Wide_data_ResistPercent, 
       aes(x = EventYear, y = Percent_Resistant)) + 
  geom_col() + 
  facet_wrap(~Region)

# Facet with Years
  
```

#Trying other variables: Age Category
```{r}
#Regroup Resist_Regional by AgeCategory:
Resist_Regional <- resistance_region %>%
  select(-Lower95CI, -Upper95CI, -PercentResistant)

#Resistance Trends by Region
Resist_Regional <- Resist_Regional %>%
  filter(NumberResistant != "Insufficient Data" & NumberResistant != "None Tested" & EventYear != "All Years")

#Change data type to numerical
Resist_Regional$NumberTested <- as.numeric(as.character(Resist_Regional$NumberTested))
Resist_Regional$NumberResistant <- as.numeric(as.character(Resist_Regional$NumberResistant))

# Tidy format for Resist_Regional data 
Resist_Regional <- Resist_Regional %>%
  gather(MetricType, MetricNumber, NumberTested:NumberResistant) %>%
  filter(EventType != "All HAIs", AgeCategory != "All Ages")

# Regroup with age and year
Resist_Regional_byAge <- Resist_Regional %>%
  group_by(Region, EventYear, MetricType, AgeCategory) %>%
  summarize(TotalMetricNumber = sum(MetricNumber))

# Revert Dataset to Wide form
Wide_AgeCategory <- spread(Resist_Regional_byAge,
                                  MetricType,
                                  TotalMetricNumber)
Wide_AgeCategory <- Wide_AgeCategory %>%
  mutate(Percent_Resistant = (NumberResistant/NumberTested)*100)

# Plot Percent Resistance by AgeCaetgory (bar):
ggplot(data = Wide_AgeCategory, 
       aes(x = EventYear, y = Percent_Resistant, fill = AgeCategory)) + 
  geom_col(position = "dodge") + 
  facet_wrap(~Region)
# Plot NumberTested by AgeCaetgory (bar):
ggplot(data = Wide_AgeCategory, 
       aes(x = EventYear, y = NumberTested, fill = AgeCategory)) + 
  geom_col(position = "dodge") +
  facet_wrap(~Region)

# Plot Percent Resistance by AgeCaetgory (line):
Resist_Regional_byAge <- Resist_Regional %>%
  group_by(EventYear, MetricType, AgeCategory) %>%
  summarize(TotalMetricNumber = sum(MetricNumber))

Wide_AgeCategory <- spread(Resist_Regional_byAge,
                                  MetricType,
                                  TotalMetricNumber)
Wide_AgeCategory <- Wide_AgeCategory %>%
  mutate(Percent_Resistant = (NumberResistant/NumberTested)*100)

Wide_AgeCategory <- Wide_AgeCategory %>%
  filter(Percent_Resistant != 0)

#ggplot(data = Wide_AgeCategory, 
#       aes(x = EventYear, y = Percent_Resistant, col = AgeCategory)) + 
#  geom_line() #Don't know why it's not plotting



```

#Trying out some statistical tests
```{r}
# Chi Square:
# categorical variables: Phenotype, Region, EventType, EventYear, EventCategory


#Regroup Resist_Regional by AgeCategory:
Resist_Regional <- resistance_region %>%
  select(-Lower95CI, -Upper95CI, -PercentResistant)

#Resistance Trends by Region
Resist_Regional <- Resist_Regional %>%
  filter(NumberResistant != "Insufficient Data" & NumberResistant != "None Tested" & EventYear != "All Years")

#Change data type to numerical
Resist_Regional$NumberTested <- as.numeric(as.character(Resist_Regional$NumberTested))
Resist_Regional$NumberResistant <- as.numeric(as.character(Resist_Regional$NumberResistant))

# Tidy format for Resist_Regional data 
Resist_Regional <- Resist_Regional %>%
  gather(MetricType, MetricNumber, NumberTested:NumberResistant) %>%
  filter(EventType != "All HAIs", AgeCategory != "All Ages")


#Rearrange
Resist_Regional_test <- Resist_Regional %>%
  group_by(Phenotype, Region, MetricType, AgeCategory) %>%
  summarize(TotalMetricNumber = sum(MetricNumber))

# Revert Dataset to Wide form
Wide_test <- spread(Resist_Regional_test,
                                  MetricType,
                                  TotalMetricNumber)
Wide_test <- Wide_test %>%
  mutate(Percent_Resistant = (NumberResistant/NumberTested)*100)


```

Merging Population and Age distrubution data:
```{r}
# importing age distrib data:
agedistrib_2011 <- read.csv("~/Documents/GitHub/DoritLab_AntibioticTrends/Data/2011_agedistribution.csv")
agedistrib_2012 <- read.csv("~/Documents/GitHub/DoritLab_AntibioticTrends/Data/2012_agedistribution.csv")
agedistrib_2013 <- read.csv("~/Documents/GitHub/DoritLab_AntibioticTrends/Data/2013_agedistribution.csv")
agedistrib_2014 <- read.csv("~/Documents/GitHub/DoritLab_AntibioticTrends/Data/2014_agedistribution.csv")
# importing population data:
pop_2011 <- read.csv("~/Documents/GitHub/DoritLab_AntibioticTrends/Data/2011_populationct.csv") %>%
  select(-Total)
pop_2012 <- read.csv("~/Documents/GitHub/DoritLab_AntibioticTrends/Data/2012_populationct.csv") %>%
  select(-Total)
pop_2013 <- read.csv("~/Documents/GitHub/DoritLab_AntibioticTrends/Data/2013_populationct.csv") %>%
  select(-Total)
pop_2014 <- read.csv("~/Documents/GitHub/DoritLab_AntibioticTrends/Data/2014_populationct.csv") %>%
  select(-Total)

#Splitting up the regional
resistance_2011 <- resistance_state %>%
  filter(EventYear == 2011,
         AgeCategory != "All Ages") %>%
  select(-Lower95CI, -Upper95CI) %>%
  mutate(Location = recode(State, 
                        "AL" = "Alabama",
                        "AK" = "Alaska",
                        "AZ" = "Arizona",
                        "AR" = "Arkansas",
                        "CA" = "California",
                        "CO" = "Colorado",
                        "CT" = "Connecticut",
                        "DE" = "Delaware",
                        "DC" = "District Of Columbia",
                        "FL" = "Florida",
                        "GA" = "Georgia",
                        "HI" = "Hawaii",
                        "ID" = "Idaho",
                        "IL" = "Illinois",
                        "IN" = "Indiana",
                        "IA" = "Iowa",
                        "KS" = "Kansas",
                        "KY" = "Kentucky",
                        "LA" = "Louisiana",
                        "ME" = "Maine",
                        "MD" = "Maryland",
                        "MA" = "Massachusetts",
                        "MI" = "Michigan",
                        "MN" = "Minnesota",
                        "MS" = "Mississippi",
                        "MO" = "Missouri",
                        "MT" = "Montana",
                        "NE" = "Nebraska",
                        "NV" = "Nevada",
                        "NH" = "New Hampshire",
                        "NJ" = "New Jersey",
                        "NM" = "New Mexico",
                        "NY" = "New York",
                        "NC" = "North Carolina",
                        "ND" = "North Dakota",
                        "OH" = "Ohio",
                        "OK" = "Oklahoma",
                        "OR" = "Oregon",
                        "PA" = "Pennsylvania",
                        "RI" = "Rhode Island",
                        "SC" = "South Carolina",
                        "SD" = "South Dakota",
                        "TN" = "Tennessee",
                        "TX" = "Texas",
                        "UT" = "Utah",
                        "VT" = "Vermont",
                        "VA" = "Virginia",
                        "WA" = "Washington",
                        "WV" = "West Virginia",
                        "WI" = "Wisconsin",
                        "WY" = "Wyoming")) %>%
  select(-State, - PercentResistant)

# Rearrange pop_2011 and agedistrib_2011 to be tidy
pop_2011 <- pop_2011 %>%
  gather(AgeCategory, Population, Children.0.18:X65.)
agedistrib_2011 <- agedistrib_2011 %>%
  gather(AgeCategory, AgeDistribution, Children.0.18:X65.)

# Combining pop_2011 and agedistrib_2011
pop_2011 <- pop_2011 %>%
  left_join(agedistrib_2011, by = c("Location", "Year", "AgeCategory"))

# Regrouping AgeCategory to :
pop_2011 <- pop_2011 %>%
  mutate(AgeCategory1 = recode(AgeCategory, "Children.0.18" = "0-18",
                              "Adults.19.25" = "19-64",
                              "Adults.26.34" = "19-64",
                              "Adults.35.54" = "19-64",
                              "Adults.55.64" = "19-64",
                              "X65." = "65+")) %>%
  select(-AgeCategory) %>%
  rename(AgeCategory = AgeCategory1,
         EventYear = Year) %>%
  group_by(Location, EventYear, AgeCategory) %>%
  summarize(pop_count = sum(Population),
            agedistribution = sum(AgeDistribution))

#pop_2011[c("Location", "EventYear", "AgeCategory","Population", "AgeDistribution")] <- reordering failed

# rename resistance_2011 agecategory values
resistance_2011$NumberTested <- as.numeric(as.character(resistance_2011$NumberTested))
resistance_2011$NumberResistant <- as.numeric(as.character(resistance_2011$NumberResistant))

resistance_2011 <- resistance_2011 %>%
  mutate(AgeCategory1 = recode(AgeCategory, 
                              "<1" = "0-18",
                              " 1-18" = "0-18")) %>%
  select(-AgeCategory) %>%
  rename(AgeCategory = AgeCategory1) %>%
  group_by(Phenotype, EventType, Location, EventYear, 
           AgeCategory, NumberTested, NumberResistant) %>%
  summarize(numberTested = sum(NumberTested),
            numberResistant = sum(NumberResistant))

resistance_2011 <- resistance_2011 %>%
  group_by(Phenotype, EventType, Location, EventYear, 
           AgeCategory, numberTested, numberResistant) %>%
  select(-NumberResistant, -NumberTested)


# merging pop_2011 to resistance_2011:
resistance_2011$EventYear <- as.character(resistance_2011$EventYear)
pop_2011$EventYear <- as.character(pop_2011$EventYear)

resistance_2011 <- resistance_2011 %>%
  left_join(pop_2011, by = c("Location", "EventYear", "AgeCategory"))

```

```{r}
## YEAR 2012

resistance_2012 <- resistance_state %>%
  filter(EventYear == 2012,
         AgeCategory != "All Ages") %>%
  select(-Lower95CI, -Upper95CI) %>%
  mutate(Location = recode(State, 
                        "AL" = "Alabama",
                        "AK" = "Alaska",
                        "AZ" = "Arizona",
                        "AR" = "Arkansas",
                        "CA" = "California",
                        "CO" = "Colorado",
                        "CT" = "Connecticut",
                        "DE" = "Delaware",
                        "DC" = "District Of Columbia",
                        "FL" = "Florida",
                        "GA" = "Georgia",
                        "HI" = "Hawaii",
                        "ID" = "Idaho",
                        "IL" = "Illinois",
                        "IN" = "Indiana",
                        "IA" = "Iowa",
                        "KS" = "Kansas",
                        "KY" = "Kentucky",
                        "LA" = "Louisiana",
                        "ME" = "Maine",
                        "MD" = "Maryland",
                        "MA" = "Massachusetts",
                        "MI" = "Michigan",
                        "MN" = "Minnesota",
                        "MS" = "Mississippi",
                        "MO" = "Missouri",
                        "MT" = "Montana",
                        "NE" = "Nebraska",
                        "NV" = "Nevada",
                        "NH" = "New Hampshire",
                        "NJ" = "New Jersey",
                        "NM" = "New Mexico",
                        "NY" = "New York",
                        "NC" = "North Carolina",
                        "ND" = "North Dakota",
                        "OH" = "Ohio",
                        "OK" = "Oklahoma",
                        "OR" = "Oregon",
                        "PA" = "Pennsylvania",
                        "RI" = "Rhode Island",
                        "SC" = "South Carolina",
                        "SD" = "South Dakota",
                        "TN" = "Tennessee",
                        "TX" = "Texas",
                        "UT" = "Utah",
                        "VT" = "Vermont",
                        "VA" = "Virginia",
                        "WA" = "Washington",
                        "WV" = "West Virginia",
                        "WI" = "Wisconsin",
                        "WY" = "Wyoming")) %>%
  select(-State, - PercentResistant)

pop_2012 <- pop_2012 %>%
  gather(AgeCategory, Population, Children.0.18:X65.)
agedistrib_2012 <- agedistrib_2012 %>%
  gather(AgeCategory, AgeDistribution, Children.0.18:X65.)

pop_2012 <- pop_2012 %>%
  left_join(agedistrib_2012, by = c("Location", "Year", "AgeCategory"))

pop_2012 <- pop_2012 %>%
  mutate(AgeCategory1 = recode(AgeCategory, "Children.0.18" = "0-18",
                              "Adults.19.25" = "19-64",
                              "Adults.26.34" = "19-64",
                              "Adults.35.54" = "19-64",
                              "Adults.55.64" = "19-64",
                              "X65." = "65+")) %>%
  select(-AgeCategory) %>%
  rename(AgeCategory = AgeCategory1,
         EventYear = Year) %>%
  group_by(Location, EventYear, AgeCategory) %>%
  summarize(pop_count = sum(Population),
            agedistribution = sum(AgeDistribution))

resistance_2012$NumberTested <- as.numeric(as.character(resistance_2012$NumberTested))
resistance_2012$NumberResistant <- as.numeric(as.character(resistance_2012$NumberResistant))

resistance_2012 <- resistance_2012 %>%
  mutate(AgeCategory1 = recode(AgeCategory, 
                              "<1" = "0-18",
                              " 1-18" = "0-18")) %>%
  select(-AgeCategory) %>%
  rename(AgeCategory = AgeCategory1) %>%
  group_by(Phenotype, EventType, Location, EventYear, 
           AgeCategory, NumberTested, NumberResistant) %>%
  summarize(numberTested = sum(NumberTested),
            numberResistant = sum(NumberResistant))

resistance_2012 <- resistance_2012 %>%
  group_by(Phenotype, EventType, Location, EventYear, 
           AgeCategory, numberTested, numberResistant) %>%
  select(-NumberResistant, -NumberTested)


resistance_2012$EventYear <- as.character(resistance_2012$EventYear)
pop_2012$EventYear <- as.character(pop_2012$EventYear)

resistance_2012 <- resistance_2012 %>%
  left_join(pop_2012, by = c("Location", "EventYear", "AgeCategory"))

## YEAR 2013


resistance_2013 <- resistance_state %>%
  filter(EventYear == 2013,
         AgeCategory != "All Ages") %>%
  select(-Lower95CI, -Upper95CI) %>%
  mutate(Location = recode(State, 
                        "AL" = "Alabama",
                        "AK" = "Alaska",
                        "AZ" = "Arizona",
                        "AR" = "Arkansas",
                        "CA" = "California",
                        "CO" = "Colorado",
                        "CT" = "Connecticut",
                        "DE" = "Delaware",
                        "DC" = "District Of Columbia",
                        "FL" = "Florida",
                        "GA" = "Georgia",
                        "HI" = "Hawaii",
                        "ID" = "Idaho",
                        "IL" = "Illinois",
                        "IN" = "Indiana",
                        "IA" = "Iowa",
                        "KS" = "Kansas",
                        "KY" = "Kentucky",
                        "LA" = "Louisiana",
                        "ME" = "Maine",
                        "MD" = "Maryland",
                        "MA" = "Massachusetts",
                        "MI" = "Michigan",
                        "MN" = "Minnesota",
                        "MS" = "Mississippi",
                        "MO" = "Missouri",
                        "MT" = "Montana",
                        "NE" = "Nebraska",
                        "NV" = "Nevada",
                        "NH" = "New Hampshire",
                        "NJ" = "New Jersey",
                        "NM" = "New Mexico",
                        "NY" = "New York",
                        "NC" = "North Carolina",
                        "ND" = "North Dakota",
                        "OH" = "Ohio",
                        "OK" = "Oklahoma",
                        "OR" = "Oregon",
                        "PA" = "Pennsylvania",
                        "RI" = "Rhode Island",
                        "SC" = "South Carolina",
                        "SD" = "South Dakota",
                        "TN" = "Tennessee",
                        "TX" = "Texas",
                        "UT" = "Utah",
                        "VT" = "Vermont",
                        "VA" = "Virginia",
                        "WA" = "Washington",
                        "WV" = "West Virginia",
                        "WI" = "Wisconsin",
                        "WY" = "Wyoming")) %>%
  select(-State, - PercentResistant)

pop_2013 <- pop_2013 %>%
  gather(AgeCategory, Population, Children.0.18:X65.)
agedistrib_2013 <- agedistrib_2013 %>%
  gather(AgeCategory, AgeDistribution, Children.0.18:X65.)

pop_2013 <- pop_2013 %>%
  left_join(agedistrib_2013, by = c("Location", "Year", "AgeCategory"))

pop_2013 <- pop_2013 %>%
  mutate(AgeCategory1 = recode(AgeCategory, "Children.0.18" = "0-18",
                              "Adults.19.25" = "19-64",
                              "Adults.26.34" = "19-64",
                              "Adults.35.54" = "19-64",
                              "Adults.55.64" = "19-64",
                              "X65." = "65+")) %>%
  select(-AgeCategory) %>%
  rename(AgeCategory = AgeCategory1,
         EventYear = Year) %>%
  group_by(Location, EventYear, AgeCategory) %>%
  summarize(pop_count = sum(Population),
            agedistribution = sum(AgeDistribution))

resistance_2013$NumberTested <- as.numeric(as.character(resistance_2013$NumberTested))
resistance_2013$NumberResistant <- as.numeric(as.character(resistance_2013$NumberResistant))

resistance_2013 <- resistance_2013 %>%
  mutate(AgeCategory1 = recode(AgeCategory, 
                              "<1" = "0-18",
                              " 1-18" = "0-18")) %>%
  select(-AgeCategory) %>%
  rename(AgeCategory = AgeCategory1) %>%
  group_by(Phenotype, EventType, Location, EventYear, 
           AgeCategory, NumberTested, NumberResistant) %>%
  summarize(numberTested = sum(NumberTested),
            numberResistant = sum(NumberResistant))

resistance_2013 <- resistance_2013 %>%
  group_by(Phenotype, EventType, Location, EventYear, 
           AgeCategory, numberTested, numberResistant) %>%
  select(-NumberResistant, -NumberTested)


resistance_2013$EventYear <- as.character(resistance_2013$EventYear)
pop_2013$EventYear <- as.character(pop_2013$EventYear)

resistance_2013 <- resistance_2013 %>%
  left_join(pop_2013, by = c("Location", "EventYear", "AgeCategory"))

## YEAR 2014


resistance_2014 <- resistance_state %>%
  filter(EventYear == 2014,
         AgeCategory != "All Ages") %>%
  select(-Lower95CI, -Upper95CI) %>%
  mutate(Location = recode(State, 
                        "AL" = "Alabama",
                        "AK" = "Alaska",
                        "AZ" = "Arizona",
                        "AR" = "Arkansas",
                        "CA" = "California",
                        "CO" = "Colorado",
                        "CT" = "Connecticut",
                        "DE" = "Delaware",
                        "DC" = "District Of Columbia",
                        "FL" = "Florida",
                        "GA" = "Georgia",
                        "HI" = "Hawaii",
                        "ID" = "Idaho",
                        "IL" = "Illinois",
                        "IN" = "Indiana",
                        "IA" = "Iowa",
                        "KS" = "Kansas",
                        "KY" = "Kentucky",
                        "LA" = "Louisiana",
                        "ME" = "Maine",
                        "MD" = "Maryland",
                        "MA" = "Massachusetts",
                        "MI" = "Michigan",
                        "MN" = "Minnesota",
                        "MS" = "Mississippi",
                        "MO" = "Missouri",
                        "MT" = "Montana",
                        "NE" = "Nebraska",
                        "NV" = "Nevada",
                        "NH" = "New Hampshire",
                        "NJ" = "New Jersey",
                        "NM" = "New Mexico",
                        "NY" = "New York",
                        "NC" = "North Carolina",
                        "ND" = "North Dakota",
                        "OH" = "Ohio",
                        "OK" = "Oklahoma",
                        "OR" = "Oregon",
                        "PA" = "Pennsylvania",
                        "RI" = "Rhode Island",
                        "SC" = "South Carolina",
                        "SD" = "South Dakota",
                        "TN" = "Tennessee",
                        "TX" = "Texas",
                        "UT" = "Utah",
                        "VT" = "Vermont",
                        "VA" = "Virginia",
                        "WA" = "Washington",
                        "WV" = "West Virginia",
                        "WI" = "Wisconsin",
                        "WY" = "Wyoming")) %>%
  select(-State, - PercentResistant)

pop_2014 <- pop_2014 %>%
  gather(AgeCategory, Population, Children.0.18:X65.)
agedistrib_2014 <- agedistrib_2014 %>%
  gather(AgeCategory, AgeDistribution, Children.0.18:X65.)

pop_2014 <- pop_2014 %>%
  left_join(agedistrib_2014, by = c("Location", "Year", "AgeCategory"))

pop_2014 <- pop_2014 %>%
  mutate(AgeCategory1 = recode(AgeCategory, "Children.0.18" = "0-18",
                              "Adults.19.25" = "19-64",
                              "Adults.26.34" = "19-64",
                              "Adults.35.54" = "19-64",
                              "Adults.55.64" = "19-64",
                              "X65." = "65+")) %>%
  select(-AgeCategory) %>%
  rename(AgeCategory = AgeCategory1,
         EventYear = Year) %>%
  group_by(Location, EventYear, AgeCategory) %>%
  summarize(pop_count = sum(Population),
            agedistribution = sum(AgeDistribution))

resistance_2014$NumberTested <- as.numeric(as.character(resistance_2014$NumberTested))
resistance_2014$NumberResistant <- as.numeric(as.character(resistance_2014$NumberResistant))

resistance_2014 <- resistance_2014 %>%
  mutate(AgeCategory1 = recode(AgeCategory, 
                              "<1" = "0-18",
                              " 1-18" = "0-18")) %>%
  select(-AgeCategory) %>%
  rename(AgeCategory = AgeCategory1) %>%
  group_by(Phenotype, EventType, Location, EventYear, 
           AgeCategory, NumberTested, NumberResistant) %>%
  summarize(numberTested = sum(NumberTested),
            numberResistant = sum(NumberResistant))

resistance_2014 <- resistance_2014 %>%
  group_by(Phenotype, EventType, Location, EventYear, 
           AgeCategory, numberTested, numberResistant) %>%
  select(-NumberResistant, -NumberTested)


resistance_2014$EventYear <- as.character(resistance_2014$EventYear)
pop_2014$EventYear <- as.character(pop_2014$EventYear)

resistance_2014 <- resistance_2014 %>%
  left_join(pop_2014, by = c("Location", "EventYear", "AgeCategory"))

```

MERGING 2011-2014 Data
```{r}
#merging rows

resistance_total <- rbind(resistance_2011, resistance_2012,
                          resistance_2013, resistance_2014)

```


Multiple Imputation:
```{r}
# removing all HAIs:
resistance_total <- resistance_total %>%
  filter(EventType != "All HAIs")

resistance_total$Phenotype <- as.character(resistance_total$Phenotype)
resistance_total$EventType <- as.character(resistance_total$EventType)
resistance_total$Location <- as.character(resistance_total$Location)
resistance_total$EventYear <- as.character(resistance_total$EventYear)
resistance_total$AgeCategory <- as.character(resistance_total$AgeCategory)

# recode state to abbrev
resistance_total <- resistance_total %>%
  mutate(State = recode(Location, 
                           "Alabama" = "AL",
                           "Alaska" = "AK",
                           "Arizona" = "AZ",
                           "Arkansas" = "AR",
                           "California" = "CA",
                           "Colorado" = "CO",
                           "Connecticut" = "CT",
                           "Delaware" = "DE",
                           "District Of Columbia" = "DC",
                           "Florida" = "FL",
                           "Georgia" = "GA",
                           "Hawaii" = "HI",
                           "Idaho" = "ID",
                           "Illinois" = "IL",
                           "Indiana" = "IN", 
                           "Iowa" = "IA",
                           "Kansas" = "KS",
                           "Kentucky" = "KY",
                           "Louisiana" = "LA", 
                           "Maine" = "ME",
                           "Maryland" = "MD",
                           "Massachusetts" = "MA",
                           "Michigan" = "MI",
                           "Minnesota" = "MN",
                           "Mississippi" = "MS",
                           "Missouri" = "MO",
                           "Montana" = "MT",
                           "Nebraska" = "NE",
                           "Nevada" = "NV",
                           "New Hampshire" = "NH",
                           "New Jersey" = "NJ",
                           "New Mexico" = "NM",
                           "New York" = "NY",
                           "North Carolina" = "NC",
                           "North Dakota" = "ND",
                           "Ohio" = "OH",
                           "Oklahoma" = "OK",
                           "Oregon" = "OR",
                           "Pennsylvania" = "PA",
                           "Rhode Island" = "RI",
                           "South Carolina" = "SC",
                           "South Dakota" = "SD",
                           "Tennessee" = "TN",
                           "Texas" = "TX",
                           "Utah" = "UT",
                           "Vermont" = "VT",
                           "Virginia" = "VA",
                           "Washington" = "WA",
                           "West Virginia" = "WV",
                           "Wisconsin" = "WI",
                           "Wyoming" = "WY")) %>%
  mutate(Region = ifelse(State %in% c("IL", "IN", "MI", "OH", "WI"), "East North Central",
                         ifelse(State %in% c("AL", "KY", "MS", "TN"), "East South Central",
                                ifelse(State %in% c("NJ", "NY", "PA"), "Middle Atlantic",
                                       ifelse(State %in% c("AZ", "CO", "ID", "MT", "NV", "NM", "UT", "WY"), "Mountain",
                                              ifelse(State %in% c("CT", "ME", "MA", "NH", "RI", "VT"), "New England",
                                                     ifelse(State %in% c("AK", "CA", "HI", "OR", "WA"), "Pacific",
                                                            ifelse(State %in% c("DE", "DC", "FL", "GA", "MD", "NC", "SC", "VA", "WV"), "South Atlantic",
                                                                   ifelse(State %in% c("IA", "KS", "MN", "MO", "NE", "ND", "SD"), "West North Central",
                                                                          ifelse(State %in% c("AR", "LA", "OK", "TX"), "West South Central", "Region Undefined"))))))))))

# reordering
col_order <- c("Phenotype", "EventType", "Location", "State", "Region", "EventYear", "AgeCategory", "numberTested", "numberResistant", "pop_count", "agedistribution")

resistance_total <- resistance_total[, col_order]

# Finding the means of numberTested and number Resistant by REGION and AGE:

summary_region_mean <- resistance_total %>%
  group_by(Region, AgeCategory) %>%
  summarize(AvgNumTested = mean(numberTested, na.rm = TRUE),
            AvgNumResistant = mean(numberResistant, na.rm = TRUE))



# With plyr package:
plyr_resistance_total <- ddply(resistance_total,~ Phenotype  +  EventType + Location + EventYear + AgeCategory,
      summarise,average=mean(numberTested)) 

```












